{"uuid": "a9f02d75-65f3-412b-96eb-e4ec19bd141d", "children": ["d8a63ca5-bc01-4ae7-979c-c2fab80867b9"], "befores": [{"name": "db_connection", "status": "skipped", "statusDetails": {"message": "Skipped: ❌ Database connection failed: connection to server at \"auroradb1-dev-staging-instance-1-eu-west-2b.callx7p4ov2n.eu-west-2.rds.amazonaws.com\" (10.4.21.227), port 3306 failed: received invalid response to SSL negotiation: J\n\n", "trace": "  File \"/Users/saravanakumar.veluchamy/Downloads/playwrightbddpython/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/saravanakumar.veluchamy/Downloads/playwrightbddpython/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/Users/saravanakumar.veluchamy/Downloads/playwrightbddpython/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ~~~~~~~~~~~~~~~~~^^\n  File \"/Users/saravanakumar.veluchamy/Downloads/playwrightbddpython/venv/lib/python3.13/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/Users/saravanakumar.veluchamy/Downloads/playwrightbddpython/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/saravanakumar.veluchamy/Downloads/playwrightbddpython/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/Users/saravanakumar.veluchamy/Downloads/playwrightbddpython/venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/saravanakumar.veluchamy/Downloads/playwrightbddpython/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/saravanakumar.veluchamy/Downloads/playwrightbddpython/venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/saravanakumar.veluchamy/Downloads/playwrightbddpython/venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 923, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/saravanakumar.veluchamy/Downloads/playwrightbddpython/tests/db/fixtures.py\", line 47, in db_connection\n    pytest.skip(f\"❌ Database connection failed: {e}\")\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/saravanakumar.veluchamy/Downloads/playwrightbddpython/venv/lib/python3.13/site-packages/_pytest/outcomes.py\", line 159, in skip\n    raise Skipped(msg=reason, allow_module_level=allow_module_level)\n"}, "start": 1760701362212, "stop": 1760701363945}], "start": 1760701362212, "stop": 1760701363963}